name: Run Scheduled Colab Notebook

on:
  schedule:
    - cron: "0 12 * * *"  # Every day at 12:00 UTC
  workflow_dispatch:       # Manual trigger option

permissions:
  contents: write           # 👈 Needed to allow push to repo

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install nbconvert nbformat ipykernel jupyter openpyxl

    - name: Execute notebook
      run: |
        jupyter nbconvert \
          --to notebook \
          --execute Untitled2.ipynb \
          --output executed_notebook.ipynb \
          --ExecutePreprocessor.timeout=300 \
          --ExecutePreprocessor.allow_errors=False










